### ISSUE TITLE
关于dubbo_provider.xml和dubbo_consumer.xml的疑问

### ISSUE THREAD

**Issue by xinuo** [wesley5201314/dubbo#1]
你好,我是刚入门dubbo的初学者.
在网络上看到你的教程,想请教一下这两个xml的配置.
在provider和consumer的xml里,都需要有 "声明需要暴露的服务接口" 这个配置.
怎么理解这个接口呢.不是应该只要provider暴露出来,我们consumer就能访问了吗?而consumer也要配置在xml里是为什么呢?

**Comment by wesley5201314** [comment]
provider中的配置

```
    <!-- 声明需要暴露的服务接口 -->
<dubbo:service interface="com.dubbo.demo.service.TestService" ref="testService" />

<!-- 具体的实现bean -->
<bean id="testService" class="com.dubbo.demo.service.impl.TestServiceImpl" />
```

这个是把我们的服务注册到zk注册中心，同时暴露出接口。
而consumer中的配置是我们调用这个接口，首先我们要找到这个接口所以需要再次声明。并交给我们的spring去注入这个服务，来供我们调用。

**Comment by xinuo** [comment]
那么,我能不能理解为:
provider和consumer都是调用dubbo_api的包里的com.dubbo.demo.service.TestService这个类的方法.
所以都在xml里交给spring注入呢?

**Comment by wesley5201314** [comment]
可以的，其实就是交给spring注入，一个是提供服务（提供服务需要提供服务的具体实现，那样我们在用的时候才能正常使用），一个使用服务（使用服务需要告诉spring你要用那个服务，让它帮助我们找到这个服务并注入到项目），不知道这样是否说的明白，我也是刚开始学习不久~一起进步

**Comment by xinuo** [comment]
嗯.明白了.3Q
